//-------------------------------------------------------------------------------
// namespace map_waste
//
// Namespace containing functions and globals for the Waste Reservoir map.
//
// jdischler | Jan, Feb 2005
//-------------------------------------------------------------------------------



void spawn_wave1(){
	sys.spawn("monsters_strogg_marine");


}
namespace map_waste
{

//-------------------------------------------------------------------------------
// Prep any level related things
//
// jdischler | Jan 2005
//-------------------------------------------------------------------------------
void main()
{
	//spawn_wave1();
	sys.trigger($waves_1);
}



} // end namespace map_waste
