//-------------------------------------------------------------------------------
// namespace map_waste
//
// Namespace containing functions and globals for the Waste Reservoir map.
//
// jdischler | Jan, Feb 2005
//-------------------------------------------------------------------------------




namespace map_waste

//-------------------------------------------------------------------------------
// Prep any level related things
//
// jdischler | Jan 2005
//-------------------------------------------------------------------------------



{
void spawn_wave1(){
	
	sys.trigger($waves_1);
	
}

void base_health(){
	float health = $base.getHealth();
	sys.wait(50);
	while(health>0)
	{
		sys.print(health);
		health = $base.getHealth();
	}	

}
void main()
{	//thread base_health();
	$base.becomePassive(1);
	spawn_wave1();
	
	//sys.trigger($waves_1);
}



} // end namespace map_waste
