//-------------------------------------------------------------------------------
// namespace map_waste
//
// Namespace containing functions and globals for the Waste Reservoir map.
//
// jdischler | Jan, Feb 2005
//-------------------------------------------------------------------------------




namespace map_waste0

//-------------------------------------------------------------------------------
// Prep any level related things
//
// jdischler | Jan 2005
//-------------------------------------------------------------------------------



{
void spawn_wave1(){
	
	sys.trigger($waves_1);
	
}
void first_wait(){
	sys.wait(30);
	sys.trigger($waves_2);
	sys.trigger($waves_1);
}

void second_wait(){
	sys.wait(30);
	sys.trigger($waves_3);
	sys.trigger($waves_4);
}

void end_game(){

}

void main()
{	
	$base.becomePassive(1);
	//sys.print($base.health)
	spawn_wave1();
	
	//sys.trigger($waves_1);
}



} // end namespace map_waste0
